apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: minimal-ingress
  annotations:
    nginx.ingress.kubernates.io/rewrite-target: /
spec:
  rules:
    #  - host: 
  - http:
      paths:
        - path: /*
          backend:
            serviceName: go-api
            servicePort: 8080

